name: qrollcall
description: "A QR Attendance Tracking App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
